services:
  redis:
    image: redis:7.2.4-alpine
    profiles: [ sentry ]

  sentry:
    image: sentry:9.1.2
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    ports:
      - "9000:9000"
    stdin_open: true
    tty: true
    environment:
      SENTRY_SECRET_KEY: 'secret'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_NAME: sentry
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis
    volumes:
      - sentry-data:/var/lib/sentry/files
    profiles: [ sentry ]

  cron:
    image: sentry:9.1.2
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    command: sentry run cron
    environment:
      SENTRY_SECRET_KEY: 'secret'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_NAME: sentry
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis
    volumes:
      - sentry-data:/var/lib/sentry/files
    profiles: [ sentry ]

  sentry-worker:
    image: sentry:9.1.2
    depends_on:
      - redis
      - postgres
    links:
     - redis
     - postgres
    command: sentry run worker
    environment:
      SENTRY_SECRET_KEY: 'secret'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_NAME: sentry
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis
    volumes:
      - sentry-data:/var/lib/sentry/files
    profiles: [ sentry ]

volumes:
  sentry-data:
